# Generated by Django 3.0.8 on 2020-07-13 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0003_auto_20200713_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Endpoint')),
            ],
            options={
                'ordering': ('timestamp',),
                'unique_together': {('endpoint', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='HTTPInspectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_ip', models.CharField(max_length=32)),
                ('connection_status', models.CharField(
                    choices=[('SUCCEED', 'SUCCEED'), ('CONN-FAILED', 'CONN-FAILED'), ('TIMED-OUT', 'TIMED-OUT')],
                    max_length=16)),
                ('status_code', models.CharField(max_length=4, null=True)),
                ('response_time', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('byte_received', models.PositiveIntegerField(null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('agent',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Agent')),
                ('inspection',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_results',
                                   to='inspecting.Inspection')),
            ],
            options={
                'ordering': ('submitted_at',),
                'unique_together': {('inspection', 'agent_ip')},
            },
        ),
    ]
