# Generated by Django 3.0.8 on 2020-07-13 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('monitoring', '0003_auto_20200713_1936'),
        ('inspecting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections',
                                    to='monitoring.Endpoint'),
        ),
    ]
