# Generated by Django 3.0.8 on 2020-07-12 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text='Human readable slug for Endpoint', unique=True, verbose_name='Endpoint name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.SlugField(max_length=64, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveIntegerField(default=30, verbose_name='Interval in seconds')),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policy', to='monitoring.Endpoint')),
                ('groups', models.ManyToManyField(related_name='_monitoringpolicy_groups_+', to='monitoring.Group')),
            ],
        ),
        migrations.CreateModel(
            name='HTTPEndpointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='Hostname')),
                ('port', models.CharField(max_length=5, verbose_name='Port')),
                ('path', models.CharField(max_length=128, verbose_name='URL Path')),
                ('method_name', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=8, verbose_name='HTTP Method name')),
                ('tls', models.BooleanField(default=True)),
                ('maximum_expected_timeout', models.IntegerField(default=30000)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='http_details', to='monitoring.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP Address')),
                ('name', models.CharField(max_length=64, verbose_name='Agent name')),
                ('country', models.CharField(max_length=3, verbose_name='Country code')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(related_name='agents', to='monitoring.Group')),
            ],
            options={
                'ordering': ('-last_activity',),
            },
        ),
    ]
