# Generated by Django 3.0.8 on 2020-07-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text='Human readable slug for Endpoint', verbose_name='Endpoint name')),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonitoringPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_selector', models.CharField(help_text='Examples: europe.* or hetzner.* depending on how you '
                                                              'defined your agents namespaces', max_length=64)),
                ('interval', models.IntegerField(default=15, verbose_name='Interval in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='monitoring_policy', to='monitoring.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='HTTPEndpointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='Hostname')),
                ('path', models.CharField(max_length=128, verbose_name='URL Path')),
                ('port', models.CharField(max_length=5, verbose_name='Port')),
                ('method_name', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=8,
                                                 verbose_name='HTTP Method name')),
                ('tls', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='http_details', to='monitoring.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.SlugField(help_text='Unique Human readable slug for agent', primary_key=True,
                                          serialize=False, verbose_name='Agent ID')),
                ('namespace', models.CharField(default='global', help_text='Examples: europe.germany.hetzner',
                                               max_length=64)),
                ('url', models.URLField(verbose_name='Agent Access URL')),
                ('token', models.CharField(max_length=128)),
                ('status',
                 models.CharField(choices=[('ACTIVE', 'Active Agent'), ('INACTIVE', 'Inactive Agent')], max_length=16)),
                ('details', models.TextField(default='', help_text='last access information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'index_together': {('status',), ('namespace',), ('status', 'namespace')},
            },
        ),
    ]
