# Generated by Django 3.0.8 on 2020-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitoring', '0002_auto_20200712_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringpolicy',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='_monitoringpolicy_groups_+', to='monitoring.Group'),
        ),
    ]
